---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: postgres:10.14-alpine
        imagePullPolicy: Never
        env:
          - name: POSTGRES_USER
            value: hello_flask
          - name: POSTGRES_DB
            value: hello_flask_dev
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flaskapi-secrets
                key: db_root_password
        ports:
        - containerPort: 5432
          name: pgsql-container
        volumeMounts:
          - name: pgsql-persistent-storage
            mountPath: /var/lib/postgresql/data/
      volumes:
        - name: pgsql-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-data-claim


---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: pgsql
  selector:
    app: pgsql
  type: LoadBalancer